### ISSUE TITLE
Lightning CSS errors when adding keyframe animations

### ISSUE THREAD

**Issue by lukebennett88** [tokenami/tokenami#235]
I have the following CSS animation to mimic some steam rising:
https://codepen.io/lukebennett88/pen/XWQzJzm

When I try putting the animation and keyframes into Tokenami, Lightning CSS shows the following error:

```log
✦ ❯ pnpm build:css

> remix-app@ build:css /site
> pnpm tokenami --minify


> remix-app@ tokenami /site
> tokenami --output app/tokenami.css "--minify"

file:///site/node_modules/.pnpm/@tokenami+dev@0.0.37_typescript@5.4.3/node_modules/@tokenami/dev/dist/cli.js:101
  const transformed = lightning.transform({
                                ^

SyntaxError: Invalid empty selector
    at generate (file:///site/node_modules/.pnpm/@tokenami+dev@0.0.37_typescript@5.4.3/node_modules/@tokenami/dev/dist/cli.js:101:33)
    at generateStyles (file:///site/node_modules/.pnpm/@tokenami+dev@0.0.37_typescript@5.4.3/node_modules/@tokenami/dev/dist/cli.js:332:18)
    at CAC.<anonymous> (file:///site/node_modules/.pnpm/@tokenami+dev@0.0.37_typescript@5.4.3/node_modules/@tokenami/dev/dist/cli.js:315:5) {
  fileName: '/site/app/tokenami.css',
  source: '\n' +
    '    @layer tokenami {\n' +
    '      @keyframes steamTransform { 0%{transform:translateY(0.5rem) scale(0.9);}100%{transform:translate(-0.125rem) scale(1.1);} },@keyframes steamFade { 0%,100%{opacity:0;}50%{opacity:1;} }\n' +
    "      :root{--_grid:0.0625rem;--anim_steamRise:3s ease-in-out infinite steamFade, 3s cubic-bezier(0.4, 0, 0.2, 1) infinite steamTransform;--background-color_accent:color(display-p3 0.9 0.45 0.2);--background-color_neutral:color(display-p3 0.992 0.992 0.989);--font-family_rounded:ui-rounded, 'Hiragino Maru Gothic ProN', Quicksand, Comfortaa, Manjari, 'Arial Rounded MT', 'Arial Rounded MT Bold', Calibri, source-sans-pro, sans-serif;--font-family_sans:Avenir, Montserrat, Corbel, 'URW Gothic', source-sans-pro, sans-serif;--font-size_12:12;--font-size_14:14;--font-size_16:16;--font-size_18:18;--font-size_20:20;--font-size_24:24;--font-size_28:28;--font-size_35:35;--font-size_60:60;--leading_12:16;--leading_14:20;--leading_16:24;--leading_18:26;--leading_20:28;--leading_24:30;--leading_28:36;--leading_35:40;--leading_60:60;--size_auto:auto;--size_full:100%;--text-color_accent:color(display-p3 0.323 0.185 0.127);--text-color_neutral:color(display-p3 0.129 0.126 0.111);--tracking_12:0.0025em;--tracking_14:0em;--tracking_16:0em;--tracking_18:-0.0025em;--tracking_20:-0.005em;--tracking_24:-0.00625em;--tracking_28:-0.0075em;--tracking_35:-0.01em;--tracking_60:-0.025em;}\n" +
    '\n' +
    '      [style] { --animation: initial; --clip-path: initial; --color: initial; --display: initial; --flex: initial; --height: initial; --letter-spacing: initial; --margin: initial; --min-width: initial; --overflow: initial; --_1qh0brs: var(--bp10) var(--bp10_padding); --bp10_padding: initial; --_fj8fs5: var(--bp20) var(--bp20_padding); --bp20_padding: initial; --padding: initial; --bp10: initial; --bp20: initial; --position: initial; --text-decoration: initial; --transform-box: initial; --white-space: initial; --width: initial; --background-color: initial; --flex-grow: initial; --flex-shrink: initial; --flex-direction: initial; --font-size: initial; --font-family: initial; --line-height: initial; --align-items: initial; --border-width: initial; }\n' +
    '      @layer tk-0, tk-1, tk-2, tk-3, tk-4, tk-5, tk-6;\n' +
    '      @layer tk-selector-0, tk-selector-1, tk-selector-2, tk-selector-3, tk-selector-4, tk-selector-5, tk-selector-6;\n' +
    '\n' +
    '      @layer tk-0 { [style] { animation: var(--animation, revert-layer); } } @layer tk-0 { [style] { clip-path: var(--clip-path, revert-layer); } } @layer tk-0 { [style] { color: var(--color, revert-layer); } } @layer tk-0 { [style] { display: var(--display, revert-layer); } } @layer tk-0 { [style] { flex: var(--flex, revert-layer); } } @layer tk-0 { [style] { height: var(--height, revert-layer); } } @layer tk-0 { [style] { letter-spacing: var(--letter-spacing, revert-layer); } } @layer tk-0 { [style] { margin: var(--margin, revert-layer); } } @layer tk-0 { [style] { min-width: var(--min-width, revert-layer); } } @layer tk-0 { [style] { overflow: var(--overflow, revert-layer); } } @layer tk-0 { [style] { padding: var(--padding, revert-layer); } } @layer tk-0 { [style] { position: var(--position, revert-layer); } } @layer tk-0 { [style] { text-decoration: var(--text-decoration, revert-layer); } } @layer tk-0 { [style] { transform-box: var(--transform-box, revert-layer); } } @layer tk-0 { [style] { white-space: var(--white-space, revert-layer); } } @layer tk-0 { [style] { width: var(--width, revert-layer); } } @layer tk-1 { [style] { background-color: var(--background-color, revert-layer); } } @layer tk-1 { [style] { flex-grow: var(--flex-grow, revert-layer); } } @layer tk-1 { [style] { flex-shrink: var(--flex-shrink, revert-layer); } } @layer tk-1 { [style] { flex-direction: var(--flex-direction, revert-layer); } } @layer tk-1 { [style] { font-size: var(--font-size, revert-layer); } } @layer tk-1 { [style] { font-family: var(--font-family, revert-layer); } } @layer tk-1 { [style] { line-height: var(--line-height, revert-layer); } } @layer tk-1 { [style] { align-items: var(--align-items, revert-layer); } } @layer tk-2 { [style] { border-width: var(--border-width, revert-layer); } }\n' +
    '      @layer tk-selector-0 { [style] { padding: var(--_fj8fs5, var(--_1qh0brs, revert-layer)); } }\n' +
    '\n' +
    '      @media (min-width: 640px) { [style] { --bp10: ; } } @media (min-width: 768px) { [style] { --bp20: ; } }\n' +
    '    }\n' +
    '  ',
  loc: { line: 3, column: 129 },
  data: { type: 'SelectorError', value: { type: 'EmptySelector' } }
}

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

This is what my config file looks like:

```tsx
 // .tokenami/tokenami.config.ts
 import { createConfig } from '@tokenami/css';

export default createConfig({
  include: ['./app/**/*.{ts,tsx}'],
  keyframes: {
    steamFade: {
      '0%, 100%': { opacity: '0' },
      '50%': { opacity: '1' },
    },
    steamTransform: {
      '0%': { transform: 'translateY(0.5rem) scale(0.9)' },
      '100%': { transform: 'translate(-0.125rem) scale(1.1)' },
    },
  },
  theme: {
    anim: {
      steamRise:
        '3s ease-in-out infinite steamFade, 3s cubic-bezier(0.4, 0, 0.2, 1) infinite steamTransform',
    },
  },
});
```

**Comment by jjenzz** [comment]
good catch ☺️  fixed in v0.0.38.
